# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Boon Jia Shen
email: jiashen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about machine learning, robotics, and other causes of head damage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.boonjiashen.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
linkedin_username: boonjiashen
github_username: boonjiashen
base_s3_path: http://boonjiashen.com.s3.ap-northeast-1.amazonaws.com/

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title/
collections:
  - projects